# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi3/AstroDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi3/AstroDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi3/AstroDB/CMakeFiles /home/pi3/AstroDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi3/AstroDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/pi3/AstroDB/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named astrodb_core

# Build rule for target.
astrodb_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 astrodb_core
.PHONY : astrodb_core

# fast build rule for target.
astrodb_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/build
.PHONY : astrodb_core/fast

#=============================================================================
# Target rules for targets named astrodb

# Build rule for target.
astrodb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 astrodb
.PHONY : astrodb

# fast build rule for target.
astrodb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb.dir/build.make CMakeFiles/astrodb.dir/build
.PHONY : astrodb/fast

src/Commands.o: src/Commands.cpp.o
.PHONY : src/Commands.o

# target to build an object file
src/Commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Commands.cpp.o
.PHONY : src/Commands.cpp.o

src/Commands.i: src/Commands.cpp.i
.PHONY : src/Commands.i

# target to preprocess a source file
src/Commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Commands.cpp.i
.PHONY : src/Commands.cpp.i

src/Commands.s: src/Commands.cpp.s
.PHONY : src/Commands.s

# target to generate assembly for a file
src/Commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Commands.cpp.s
.PHONY : src/Commands.cpp.s

src/Page.o: src/Page.cpp.o
.PHONY : src/Page.o

# target to build an object file
src/Page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Page.cpp.o
.PHONY : src/Page.cpp.o

src/Page.i: src/Page.cpp.i
.PHONY : src/Page.i

# target to preprocess a source file
src/Page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Page.cpp.i
.PHONY : src/Page.cpp.i

src/Page.s: src/Page.cpp.s
.PHONY : src/Page.s

# target to generate assembly for a file
src/Page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Page.cpp.s
.PHONY : src/Page.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Storage.o: src/Storage.cpp.o
.PHONY : src/Storage.o

# target to build an object file
src/Storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Storage.cpp.o
.PHONY : src/Storage.cpp.o

src/Storage.i: src/Storage.cpp.i
.PHONY : src/Storage.i

# target to preprocess a source file
src/Storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Storage.cpp.i
.PHONY : src/Storage.cpp.i

src/Storage.s: src/Storage.cpp.s
.PHONY : src/Storage.s

# target to generate assembly for a file
src/Storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb_core.dir/build.make CMakeFiles/astrodb_core.dir/src/Storage.cpp.s
.PHONY : src/Storage.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb.dir/build.make CMakeFiles/astrodb.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb.dir/build.make CMakeFiles/astrodb.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/astrodb.dir/build.make CMakeFiles/astrodb.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... astrodb"
	@echo "... astrodb_core"
	@echo "... src/Commands.o"
	@echo "... src/Commands.i"
	@echo "... src/Commands.s"
	@echo "... src/Page.o"
	@echo "... src/Page.i"
	@echo "... src/Page.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Storage.o"
	@echo "... src/Storage.i"
	@echo "... src/Storage.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/pi3/AstroDB/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

